### ISSUE TITLE
[Epic] waku relay (node) 

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#13]
## Problem

A near real time decentralized and secure communication protocol is needed to enable dapps, wallets and other apps (e.g. chat app) to use a decentralized infrastructure while maintaining an acceptable UX,.

## Solution

Provide a JS library that allows developers to use waku v2 relay for near real time communication purposes.
Ensure the JS library is functional by including a suite of tests.
Demonstrate the usage of the API by building a CLI chat app that can communicate with the nim-waku example chat app.

For now, the solution can be focused on node support only. A separate issue will track browser support.

### Tests

Demonstrate the following features as working in test:

- [x] Publishing messages between js-waku instances #7 
- [x] Publishing messages between js-waku & nim-waku instances
- [x] Encoding/Decoding of Waku messages
- ~NAT passthrough support #12~

### Chat app

- [x] Receive and send messages from the fleet #15

## Issues

See https://github.com/status-im/js-waku/milestone/1

**Comment by D4nte** [comment]
Done!
