### ISSUE TITLE
[Epic] waku relay (browser)

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#14]
## Problem

See #13. Dapps and wallets are web apps running in desktop and mobile browser.

## Solution

To enable developers using waku relay as a communication protocol, js-waku needs to support browser environment.

## Acceptance Criteria

- ~test suite can run in browser environment~ Moved to #52
- [x] Primitive web chat app demonstrates the usage of the API

## Steps

- [x] Render list of chat messages
- [x] Render chat messages (timestamp, handle, message)
- [x] React on waku relay messages
- [x] Send messages

**Comment by D4nte** [comment]
Blocker when trying to integrated waku in the react web app: https://github.com/libp2p/js-libp2p/issues/909

Several ways to move forward
1. Wait for libp2p 0.31 release
2. Use [resolutions](https://github.com/libp2p/js-libp2p/issues/909) with [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) but it failed to override the versions. TODO: Try again without `**/`
3. Use [resolutions](https://github.com/libp2p/js-libp2p/issues/909) with yarn, however migrating to yarn [failed because of ts-proto](https://github.com/stephenh/ts-proto/issues/147#issuecomment-821078743)

At this stage, I am going to aim for 1. In the meantime, I can create a `WakuMock` and move forward with the react app and then replace the `WakuMock` once 1 is done or spend more time on workarounds.

**Comment by D4nte** [comment]
Note that for 3, ts-proto 1.79.3 should fix the issue: https://github.com/stephenh/ts-proto/pull/275
