### ISSUE TITLE
WakuMessage is missing waku pubkey and signature

### ISSUE THREAD

**Issue by bgits** [status-im/js-waku#179]
## Problem

There are no defined way to include a signature in Waku Messages.

## Solution

1. Implement Waku Message version 1 ~once it has been re-written for Waku v2: https://github.com/vacp2p/rfc/issues/373.~
1. Attempt to use Metamask encryption API instead of eth-crypto in Eth-DM example (or new example).

## Tasks

- [x] Signature. #221

### Asymmetric encryption

- [x] Asymmetric encryption/decryption. #221
- [x] Integration in Waku Relay. #221
- [x] Interop with nim-waku: parity-ecies is actually not compatible with geth/nim-eth/waku ecies encryption we used as it sets a shared hmac/auth of `[0,0]` instead of `[]`. Need to use a different lib. #223
- [x] Light push example #225
- [x] Store integration #225
- [x] Eth-DM integration #227

### Symmetric encryption

- [x] Symmetric encryption/decryption support #229
- [x] Integration in Waku Relay #231
- [x] Interop with nim-waku #231
- [x] Store integration #231
- Example app tracked with #226 

<details>
<summary>
Original issue</summary>

## Original issue

- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

`WakuMessage` is missing the Waku pubkey and message signature. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

This is useful for dapps that want to confirm origin and authenticity of message
</details>

**Comment by D4nte** [comment]
Should be sorted with #74

**Comment by D4nte** [comment]
I had more thought on that, see https://forum.vac.dev/t/eth-dm-learnings-and-what-is-next/84

**Comment by D4nte** [comment]
This may be a dupe of https://github.com/vacp2p/rfc/issues/373 actually as we have yet to define format and schema to use.

Would you want it being only signature or always coupled with encryption?

**Comment by D4nte** [comment]
@bgits can you please go in more details on your expectations here?
What signature scheme would you expect? What is your use case? We are thinking about providing a standard way to do encryption and signature with Waku (see https://github.com/vacp2p/rfc/issues/373) but we'd need more concrete information on your needs to be sure we go in the right direction.

**Comment by bgits** [comment]
> @bgits can you please go in more details on your expectations here?
> What signature scheme would you expect? What is your use case? We are thinking about providing a standard way to do encryption and signature with Waku (see [vacp2p/rfc#373](https://github.com/vacp2p/rfc/issues/373)) but we'd need more concrete information on your needs to be sure we go in the right direction.

Effectively a dapp should be able to verify a message itself (https://docs.ethers.io/v5/api/utils/signing-key/#utils-verifyMessage).

This can be used for several cases. The main cases I have in mind are around creating proofs. In applications that require data submission this could be used to create proofs that later allow submitters to claim compensation by proofing ownership of the key to claim onchain.

**Comment by D4nte** [comment]
Thanks, so your focus would be in signing using the user Ethereum's account to possibly push the data on the blockchain. Noted.

**Comment by bgits** [comment]
> Thanks, so your focus would be in signing using the user Ethereum's account to possibly push the data on the blockchain. Noted.

Not signing the Ethereum account but claiming from any Ethereum account. In order to do that they need to create a proof using their Waku key. 

Another use case could be for incentives around Waku itself. Nodes can accumulate signed messages from other nodes when relaying or storing and then reconcile occasionally on the main chain.

**Comment by oskarth** [comment]
@bgits What do you mean by "Waku key" exactly? There is no such term in https://rfc.vac.dev/spec/10/ and in https://rfc.vac.dev/spec/11/#protobuf-definitions we explicitly disable it due to `StrictNoSign` policy (privacy).

At the WakuMessage layer https://rfc.vac.dev/spec/14/#version-1 with version=1 there's a concept of keys, but key agreement is out of band. This is the same method as with Waku v1 with SECP-256k1 ECDSA and providing for asymmetric/symmetric encryption/signatures see https://rfc.vac.dev/spec/7/ and https://rfc.vac.dev/spec/6/#payload-encryption This signature is only accessible if you are able to decrypt the payload (privacy).

There is also PeerId at libp2p level which may or may not be the same https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md

For the Status protocol specifically, Whisper/Waku key is a pubkey for chat with HD derivation path m/43’/60’/1581’/0’/0 see https://specs.status.im/spec/2#terms-glossary  and https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1581.md (In addition to the double ratchet protocol, which sits on top). This isn't enforced at Waku layer, but would generally be seen as good practice to decouple Ethereum address from Chat address (though this depends on use case).

In the chat2 example only symmetric key is used and derived from the content topic, similar to Status public chats.

---

In general, I'd suggest we try to find a way to use Waku Message version 1, unless we have some fundamentally strong reasons not to. It is fairly agnostic to exactly where the keys come from etc. Using any ECSDA keypair - including Ethereum key - it should be possible to do a claim from any Ethereum account, with a combination of signatures and out of band key discovery or a derivable symmetric key (secret, pseudo-secret or transparent).

Exactly what that looks when it comes to interacting with a dapp etc I'm not 100% sure on and would require a bit more though, but it seems to me like we have all the building blocks necessary already?

**Comment by bgits** [comment]
I'm also thinking about Waku incentivization, regardless of what the design will look like, it seems there would need to be reliance on someone proving message origination. I agree speaking about keys specifically may not be the only solution, perhaps there are ways to do this in zero-knowledge as well.

**Comment by oskarth** [comment]
@bgits happy to talk/hear ideas re Waku incentivization, let's do that outside of this issue though to keep it more limited in scope

**Comment by D4nte** [comment]
Moving the discussion to the forum as I think there should be a broader discussion about encryption/signature in waku v2: https://forum.vac.dev/t/signature-and-encryption-in-waku-v2/85

**Comment by staheri14** [comment]
@bgits I saw you mentioned 
> proving message origination.

Is the message private or public? 

If it is public, then everyone can claim ownership of the message. In this case, the signature does not help. Let's say there is a message `m` that is a solution for a puzzle and anyone who knows it will be rewarded. In such a case, if someone publishes `m` and a signature on `m` cannot prove the ownership, because someone else can see and copy `m` and make a similar claim.

However, I guess you are looking for the non-repudiation property of signatures i.e., the signer of a message won't be able to deny her signed message. Then, you want to track down the signer's public key (signature verification key) and e.g., remove it from the system (some sort of punishment).  Is this what you want? 

In any case, as also @oskarth mentioned, the use of signature is disabled in waku v2 to preserve user anonymity. Otherwise, all the messages signed by the same user are linkable. We might be able to think about using zero-knowledge proof, but the use-case must be clear.  For example, in the case of voting, zero-knowledge proof of membership must work, similar to what we are doing in RLN-Relay https://rfc.vac.dev/spec/17/  https://vac.dev/rln-relay

**Comment by D4nte** [comment]
I believe this is now done, see the task list in the description.

if Waku Message version 1 lacks some characteristics that you need, please open an issue or discussion in https://github.com/vacp2p/rfc first.

If you encounter any issue using version 1 with js-waku or question, feel free to open a new issue!
