### ISSUE TITLE
[Epic] js-waku showcase

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#67]
## Objective

Provide a show case of the js-waku library that demonstrates its readiness & excites developers and users alike.

### Requirements

The show case is the chat web app. It needs to _just work_.
A user should be able to visit https://status-im.github.io/js-waku/ and start chatting with other users of the nim-waku test fleet without having to modify their browser or run any command.

While it is not expected at this at this stage that developers will start integration js-waku, the codebase should be in a state where developers can run the example app locally.

## Definition of Done

See https://github.com/status-im/js-waku/milestone/1 for all issues

- [x] Send and receive messages using waku relay
- [x] Retrieve old messages upon starting using waku store #69 
- [x] Automatically connect to a wss remote waku instance connected to nim test fleet #45 #106 #115
- [x] Work in modern browsers (Chrome, Firefox, Edge, Opera)
- [x] Provide a default (pseudo-)unique username to new users #94
- [x] Be tested by 5 users (Status or not) with reported bugs fixed
	- 0xc1c4da on Android/Bromite
	- correy on Linux/Opera
	- John on Windows/Chrome+Edge
	- GuyLouis on Mac/Brave
	- James on Android/Chrome see #136
- [x] Instructions to run the web app are present in the readme #117

**Comment by oskarth** [comment]
Looks good to me!
