### ISSUE TITLE
[Epic] Developer Ready

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#68]
## Objective

Provide documentation to allow developers to start integration js-waku in their application.

#### Tutorial

To help developer use js-waku, a tutorial to build a simple web app should be published.

The app could be a simplified version of the ReactJS chat web app, with only waku relay.

Also, as the aim is to provide easy integration with web3.js, we should have at least one functionality in js-waku that uses web3.js.

#### Stability

Review the current code todo and pending issue and flag any that seems critical for stability. Especially any task that would involve major API refactoring.

#### Documentation

Feedback has been provided on the current documentation. We need to ensure that the documentation covers the majority of the API, especially API used in examples and tutorial. We also need to review that the documentation is written for a dApp developer audience, with no knowledge of the spec; the documentation should give a function explanation of the API while referring to the spec for corner cases and advance usage.

## Definition of Done

See https://github.com/status-im/js-waku/milestone/2 for all issues

- [x] Guide to build an app that uses waku relay is written and published #56
- [x] One example (or part of tutorial) on how to use web3.js with js-waku #72
- [x] One guide to use waku store #254
- [x] One guide to use encryption
- [x] ~Guide to sign messages with web3~ One can be redirected to https://github.com/status-im/wakuconnect-vote-poll-sdk
- [x] All API/interfaces/functions used in the tutorial are documented in code @jemboh
- [x] Code documentation is available online
- [x] No untracked (by GH issue) TODO in the codebase @d4nte
- [x] API provided to easily connect to the nim-waku test fleet
- [x] ~Browser js-waku can connect directly to nim-waku (via ws, quic or https long poll see #107)~ websockify is the way for now, tutorial to install websockify added to nim-waku repo: https://github.com/status-im/nim-waku/blob/master/docs/tutorial/websocket.md

**Comment by oskarth** [comment]
Maybe some example of how to use a Metamask derived key for messaging?

**Comment by D4nte** [comment]
> Maybe some example of how to use a Metamask derived key for messaging?

We have the same idea #72

**Comment by D4nte** [comment]
All done.
