### ISSUE TITLE
Release 0.25.0

### ISSUE THREAD

**Issue by fryorcraken** [status-im/js-waku#891]
Track the blockers for the next release.

A lot of refactoring has happen since the last release:

- Migration to ESM only
- Upgrade to latest libp2p* libraries
- New API for a more modular architecture

Release candidates under the `next` flag will be published to help prepare this release.

## Tasks

Remaining tasks to do before release

- [x] Use release candidate in all examples https://github.com/waku-org/js-waku-examples/issues/56
- [x] ~Investigate issues with Waku Relay being unreliable (related to `protons` performance issue? https://github.com/ipfs/protons/issues/51)~ was actually fine when playing around with examples.
- [x] ~Use a proto encoding/decoding that handles default as expected (ref: https://github.com/ipfs/protons/pull/48)~ tracked with https://github.com/status-im/js-waku/issues/921. Not blocking as the problems encountered have been handled individually (e.g. https://github.com/status-im/js-waku/blob/d79984fdba57c8e89400fc2a47958d49e0ed9645/src/lib/waku_message/index.ts#L273)
- [x] Use `libp2p@0.38.0` once published. Not a strong blocker but a recommended one. https://github.com/status-im/js-waku/pull/922
- [x] https://github.com/status-im/js-waku/issues/895
- [x] Ensure full test suite pass https://github.com/status-im/js-waku/issues/902

**Comment by fryorcraken** [comment]
feedback from @filoozom

> On latest master, it seems a bit difficult to import createWaku.
`import { createWaku, CreateOptions } from 'js-waku/dist/lib/create_waku'` works for types, but one needs to use `import { createWaku, CreateOptions } from 'js-waku/lib/create_waku'` for the imports to actually work.
> Also, it's not quite clear how to connect to static peers., as I can't import `PeerDiscoveryStaticPeers` (maybe related to the same issue as for `createWaku`)

**Comment by fryorcraken** [comment]
https://github.com/status-im/js-waku/pull/893 helps with the proto behaviour

**Comment by fryorcraken** [comment]
export issue  https://github.com/status-im/js-waku/pull/894

**Comment by fryorcraken** [comment]
Done!
